---
- name:  Web server Setup
  hosts:  web
  become: yes
  tasks:  
    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Start Apache
      service:
        name: httpd
        enabled:  yes
        state:  started
...
