---
- name: create user in client
  hosts:  all
  vars:
    # uname:  aswathy
    #comment:  variable in playbook
  tasks:
    - name: create new user
      user:
        name: "{{uname}}"
        comment:  "{{comment}}"
      register: userout

    - debug:
        var:  userout.name
    - debug:
        var:  userout.comment
...
